name: build-and-test
run-name: Build and test ${{ github.sha }}
on: [push]

env:
  EM_VERSION: 3.1.43
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/cache@v3
        name: Cache system libraries
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}-${{github.job}}

      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          #actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
          no-cache: true

      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          key: cache-dependencies-${{ hashFiles('mk/*') }}-${{ runner.os }}-${{github.job}}
          path: build/*.tar*

      - run: make extract

      - uses: bhowell2/github-substring-action@1.0.2
        id: sha
        with:
          value: ${{ github.sha }}
          length_from_start: 7

      - run: npm test

  full-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/cache@v3
        name: Cache system libraries
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}-${{github.job}}

      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          #actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
          no-cache: true

      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          key: cache-dependencies-${{ hashFiles('mk/*') }}-${{ runner.os }}-${{github.job}}
          path: build/*.tar*

      - run: make extract

      - uses: bhowell2/github-substring-action@1.0.2
        id: sha
        with:
          value: ${{ github.sha }}
          length_from_start: 7

      - run: make release -j9 LIBAVJS_VERSION_SUFFIX=-${{ steps.sha.outputs.substring }}

      - uses: actions/upload-artifact@v3
        with:
          name: complete build
          path: libav.js-*.zip

  build-variant:
    strategy:
      matrix:
        variant: [default, lite, fat, obsolete, opus, flac, opus-flac, webm, webm-opus-flac, mediarecorder-transcoder, open-media, webcodecs, all-audio-cli, rawvideo, h265, prores, mediarecorder-transcoder, all]

    if: |
      !contains(github.event.head_commit.message, 'skip ci')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/cache@v3
        name: Cache system libraries
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}-${{github.job}}-${{matrix.variant}}

      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          #actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
          no-cache: true

      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          key: cache-dependencies-${{ hashFiles('mk/*') }}-${{ runner.os }}-${{github.job}}
          path: build/*.tar*

      - run: make extract

      - uses: bhowell2/github-substring-action@1.0.2
        id: sha
        with:
          value: ${{ github.sha }}
          length_from_start: 7

      - run: |-2
          LIBAVJS_VERSION_SUFFIX=-${{ steps.sha.outputs.substring }}
          LIBAVJS_VERSION="4.3.6.0$LIBAVJS_VERSION_SUFFIX"
          mkdir libav.js-$LIBAVJS_VERSION
          cp -a README.md docs libav.js-$LIBAVJS_VERSION/
          mkdir libav.js-$LIBAVJS_VERSION/dist
          for v in ${{matrix.variant}};
          do
            make build-$v
            cp dist/libav-$LIBAVJS_VERSION-$v.* libav.js-$LIBAVJS_VERSION/dist
          done
          cp dist/libav.types.d.ts libav.js-$LIBAVJS_VERSION/dist/
          mkdir libav.js-$LIBAVJS_VERSION/sources
          for t in ffmpeg lame libaom libogg libvorbis libvpx opus;
          do
            make $t-release
          done
          git archive HEAD -o libav.js-$LIBAVJS_VERSION/sources/libav.js.tar
          xz libav.js-$LIBAVJS_VERSION/sources/libav.js.tar
          #zip -r libav.js-$LIBAVJS_VERSION.zip libav.js-$LIBAVJS_VERSION
          #rm -rf libav.js-$LIBAVJS_VERSION

      - uses: actions/upload-artifact@v3
        with:
          name: libav.js ${{matrix.variant}}
          path: libav.js-*

  
